### ISSUE TITLE
observe tableview contentoffset

### ISSUE THREAD

**Issue by WenchaoD** [Vinodh-G/ParallaxTableViewHeader#10]
This header needs to be layout on tableview delegate, why not just add observer for the contentOffset for the tableView inside this header?

**Comment by Vinodh-G** [comment]
@WenchaoD

I have used the ParallaxTableViewHeader as a plugin to UITableView, ParallaxTableViewHeader is not interested on the scrollView offset since it is plugin view, it knows only to update itself,
The UITableView as which much interested in updating its subview  which is ParallaxTableViewHeader.

Thats why the offset is updated from UItableViewController or ViewController

**Comment by WenchaoD** [comment]
Got that. Thanks.
